### ISSUE TITLE
Add class to anchor tag?

### ISSUE THREAD

**Issue by Visiluna** [carlcs/craft-redactorinlinestyles#36]
Could _Redactor Custom Styles_ be configured to add a class to an anchor tag?

My specific use case is to add the `button` class to a selected link.

`<a href="mylink.html">Go there</a>`

becomes

`<a class="button" href="mylink.html">Go there</a>`

**Comment by carlcs** [comment]
This works better when you’re using the `"module.inline.toggle"` API (see https://imperavi.com/redactor/docs/api-modules/inline/#s-toggle).

```json
"primaryButton": {
  "api": "module.inline.toggle",
  "args": { "class": "button" }
},
```

```css
:root .redactor-styles a.button {
    padding: 7px 14px;
    color: var(--blue-800);
    text-decoration: none;
    border: 2px solid var(--blue-600);
    border-radius: var(--large-border-radius);
}
```
